import type { Metadata } from "next";
import { Ojuju } from "next/font/google";
import "@/app/ui/styles/globals.css";

// const inter = Inter({ subsets: ["latin"] });

// const roboto = Roboto({
//   weight: ['400', '700'],
//   style: ['normal'],
//   subsets: ['latin'],
//   display: 'swap',
// })

const basicFont = Ojuju({
  subsets: ['latin'],
  variable: '--font-basic',
  weight: '500',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={basicFont.className}>{children}</body>
    </html>
  );
}
